name: checkin

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install axios
        run: npm install axios

      - name: Run sign
        run: node cloud189_sign.js
        env:
          CLOUD189_COOKIE: ${{ secrets.CLOUD189_COOKIE }}
