name: HJD2048 Checkin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install flask opencv-python ddddocr
          pip install --force-reinstall -v "Pillow==9.5.0"

      - name: Start OCR service
        run: nohup python hjd2048/app.py &

      - name: Install Node dependencies
        run: |
          cd hjd2048
          npm install

      - name: Run sign
        env:
          HJD_ACCOUNT: ${{ secrets.HJD_ACCOUNT }}
          HJD_PASSWORD: ${{ secrets.HJD_PASSWORD }}
          HJD_QUESTION: ${{ secrets.HJD_QUESTION }}
          HJD_ANSWER: ${{ secrets.HJD_ANSWER }}
        run: |
          cd hjd2048
          node main.js
